language: ruby
rvm:
  - 2.4.4

bundler_args: --without production

script:
  - bundle exec nanoc compile

cache:
  - bundler

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  keep_history: true
  local_dir: output
  on:
    branch: master
